onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix decimal -childformat {{{/LinearVisualizer_testbench/noteAmplitudes[11]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[10]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[9]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[8]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[7]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[6]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[5]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[4]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[3]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[2]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[1]} -radix decimal} {{/LinearVisualizer_testbench/noteAmplitudes[0]} -radix decimal}} -subitemconfig {{/LinearVisualizer_testbench/noteAmplitudes[11]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[10]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[9]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[8]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[7]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[6]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[5]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[4]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[3]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[2]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[1]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/noteAmplitudes[0]} {-height 15 -radix decimal}} /LinearVisualizer_testbench/noteAmplitudes
add wave -noupdate -radix decimal -childformat {{{/LinearVisualizer_testbench/notePositions[11]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[10]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[9]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[8]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[7]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[6]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[5]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[4]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[3]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[2]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[1]} -radix decimal} {{/LinearVisualizer_testbench/notePositions[0]} -radix decimal}} -subitemconfig {{/LinearVisualizer_testbench/notePositions[11]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[10]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[9]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[8]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[7]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[6]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[5]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[4]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[3]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[2]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[1]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/notePositions[0]} {-height 15 -radix decimal}} /LinearVisualizer_testbench/notePositions
add wave -noupdate /LinearVisualizer_testbench/clk
add wave -noupdate /LinearVisualizer_testbench/rst
add wave -noupdate -radix unsigned -childformat {{{/LinearVisualizer_testbench/dut/amplitudes[11]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[10]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[9]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[8]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[7]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[6]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[5]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[4]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[3]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[2]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[1]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudes[0]} -radix unsigned}} -subitemconfig {{/LinearVisualizer_testbench/dut/amplitudes[11]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[10]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[9]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[8]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[7]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[6]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[5]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[4]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[3]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[2]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[1]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudes[0]} {-height 15 -radix unsigned}} /LinearVisualizer_testbench/dut/amplitudes
add wave -noupdate -radix unsigned -childformat {{{/LinearVisualizer_testbench/dut/amplitudesFast[11]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[10]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[9]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[8]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[7]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[6]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[5]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[4]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[3]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[2]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[1]} -radix unsigned} {{/LinearVisualizer_testbench/dut/amplitudesFast[0]} -radix unsigned}} -subitemconfig {{/LinearVisualizer_testbench/dut/amplitudesFast[11]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[10]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[9]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[8]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[7]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[6]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[5]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[4]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[3]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[2]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[1]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/amplitudesFast[0]} {-height 15 -radix unsigned}} /LinearVisualizer_testbench/dut/amplitudesFast
add wave -noupdate -radix unsigned /LinearVisualizer_testbench/dut/amplitudeSum
add wave -noupdate -radix unsigned -childformat {{{/LinearVisualizer_testbench/dut/hues[11]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[10]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[9]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[8]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[7]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[6]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[5]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[4]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[3]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[2]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[1]} -radix unsigned} {{/LinearVisualizer_testbench/dut/hues[0]} -radix unsigned}} -subitemconfig {{/LinearVisualizer_testbench/dut/hues[11]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[10]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[9]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[8]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[7]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[6]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[5]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[4]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[3]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[2]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[1]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/dut/hues[0]} {-height 15 -radix unsigned}} /LinearVisualizer_testbench/dut/hues
add wave -noupdate -radix unsigned -childformat {{{/LinearVisualizer_testbench/dut/LEDCounts[11]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[10]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[9]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[8]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[7]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[6]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[5]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[4]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[3]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[2]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[1]} -radix unsigned} {{/LinearVisualizer_testbench/dut/LEDCounts[0]} -radix unsigned}} -subitemconfig {{/LinearVisualizer_testbench/dut/LEDCounts[11]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[10]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[9]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[8]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[7]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[6]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[5]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[4]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[3]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[2]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[1]} {-radix unsigned} {/LinearVisualizer_testbench/dut/LEDCounts[0]} {-radix unsigned}} /LinearVisualizer_testbench/dut/LEDCounts
add wave -noupdate /LinearVisualizer_testbench/dut/rgb
add wave -noupdate /LinearVisualizer_testbench/data_v
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {101969 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 208
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {2625 ps} {1105125 ps}
