onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix unsigned -childformat {{{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[11]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[10]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[9]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[8]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[7]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[6]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[5]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[4]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[3]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[2]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[1]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[0]} -radix unsigned}} -subitemconfig {{/AmpPreprocessor_testbench/dut/noteAmplitudes_o[11]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[10]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[9]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[8]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[7]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[6]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[5]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[4]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[3]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[2]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[1]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_o[0]} {-height 15 -radix unsigned}} /AmpPreprocessor_testbench/dut/noteAmplitudes_o
add wave -noupdate -radix unsigned -childformat {{{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[11]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[10]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[9]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[8]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[7]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[6]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[5]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[4]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[3]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[2]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[1]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[0]} -radix unsigned}} -subitemconfig {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[11]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[10]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[9]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[8]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[7]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[6]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[5]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[4]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[3]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[2]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[1]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast_o[0]} {-height 15 -radix unsigned}} /AmpPreprocessor_testbench/dut/noteAmplitudesFast_o
add wave -noupdate -radix unsigned /AmpPreprocessor_testbench/dut/amplitudeSumNew_o
add wave -noupdate /AmpPreprocessor_testbench/data_v
add wave -noupdate -radix unsigned -childformat {{{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[11]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[10]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[9]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[8]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[7]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[6]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[5]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[4]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[3]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[2]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[1]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[0]} -radix unsigned}} -subitemconfig {{/AmpPreprocessor_testbench/dut/noteAmplitudes_i[11]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[10]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[9]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[8]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[7]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[6]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[5]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[4]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[3]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[2]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[1]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudes_i[0]} {-height 15 -radix unsigned}} /AmpPreprocessor_testbench/dut/noteAmplitudes_i
add wave -noupdate /AmpPreprocessor_testbench/dut/clk
add wave -noupdate /AmpPreprocessor_testbench/dut/rst
add wave -noupdate /AmpPreprocessor_testbench/dut/cycle_cntr
add wave -noupdate -expand -group Internal -radix unsigned /AmpPreprocessor_testbench/dut/amplitudeSum
add wave -noupdate -expand -group Internal -radix unsigned /AmpPreprocessor_testbench/dut/amplitudeSum_d1
add wave -noupdate -expand -group Internal -radix unsigned /AmpPreprocessor_testbench/dut/threshold_tmp
add wave -noupdate -expand -group Internal -radix unsigned /AmpPreprocessor_testbench/dut/threshold
add wave -noupdate -expand -group Internal -radix unsigned /AmpPreprocessor_testbench/dut/threshold_d1
add wave -noupdate -expand -group Internal -radix unsigned -childformat {{{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[11]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[10]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[9]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[8]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[7]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[6]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[5]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[4]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[3]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[2]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[1]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[0]} -radix unsigned}} -subitemconfig {{/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[11]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[10]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[9]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[8]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[7]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[6]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[5]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[4]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[3]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[2]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[1]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesReduced[0]} {-height 15 -radix unsigned}} /AmpPreprocessor_testbench/dut/noteAmplitudesReduced
add wave -noupdate -expand -group Internal -radix unsigned -childformat {{{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[11]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[10]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[9]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[8]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[7]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[6]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[5]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[4]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[3]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[2]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[1]} -radix unsigned} {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[0]} -radix unsigned}} -subitemconfig {{/AmpPreprocessor_testbench/dut/noteAmplitudesFast[11]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[10]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[9]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[8]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[7]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[6]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[5]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[4]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[3]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[2]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[1]} {-height 15 -radix unsigned} {/AmpPreprocessor_testbench/dut/noteAmplitudesFast[0]} {-height 15 -radix unsigned}} /AmpPreprocessor_testbench/dut/noteAmplitudesFast
add wave -noupdate -expand -group Internal -radix unsigned /AmpPreprocessor_testbench/dut/amplitudeSumNew
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {15184 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2048 ns}
