onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix unsigned -childformat {{{/LinearVisualizer_testbench/noteAmplitudes[11]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[10]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[9]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[8]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[7]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[6]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[5]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[4]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[3]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[2]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[1]} -radix unsigned} {{/LinearVisualizer_testbench/noteAmplitudes[0]} -radix unsigned}} -expand -subitemconfig {{/LinearVisualizer_testbench/noteAmplitudes[11]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[10]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[9]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[8]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[7]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[6]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[5]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[4]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[3]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[2]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[1]} {-height 15 -radix unsigned} {/LinearVisualizer_testbench/noteAmplitudes[0]} {-height 15 -radix unsigned}} /LinearVisualizer_testbench/noteAmplitudes
add wave -noupdate -radix unsigned /LinearVisualizer_testbench/dut/amplitudeSum
add wave -noupdate -radix decimal /LinearVisualizer_testbench/dut/amplitudeSumMultiplied
add wave -noupdate -radix decimal -childformat {{{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[11]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[10]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[9]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[8]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[7]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[6]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[5]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[4]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[3]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[2]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[1]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[0]} -radix decimal}} -expand -subitemconfig {{/LinearVisualizer_testbench/dut/noteAmplitudesReduced[11]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[10]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[9]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[8]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[7]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[6]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[5]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[4]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[3]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[2]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[1]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesReduced[0]} {-height 15 -radix decimal}} /LinearVisualizer_testbench/dut/noteAmplitudesReduced
add wave -noupdate -radix decimal -childformat {{{/LinearVisualizer_testbench/dut/noteAmplitudesFast[11]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[10]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[9]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[8]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[7]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[6]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[5]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[4]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[3]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[2]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[1]} -radix decimal} {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[0]} -radix decimal}} -expand -subitemconfig {{/LinearVisualizer_testbench/dut/noteAmplitudesFast[11]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[10]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[9]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[8]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[7]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[6]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[5]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[4]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[3]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[2]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[1]} {-height 15 -radix decimal} {/LinearVisualizer_testbench/dut/noteAmplitudesFast[0]} {-height 15 -radix decimal}} /LinearVisualizer_testbench/dut/noteAmplitudesFast
add wave -noupdate -radix decimal /LinearVisualizer_testbench/dut/amplitudeSumNew
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {58 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 208
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {40 ps} {108 ps}
